name: ChangeDisplayName

main: Wertzui123\ChangeDisplayName\Main

version: 0.0.2

api: 3.0.0

load: POSTWORLD

author: Wertzui123

description: A plugin to change your displayname in-game!

website: https://github.com/Wertzui123/ChangeDisplayName

commands:
 changedisplayname:

  description: "Change your displayname in-game"
  aliases: [cdn, nick]
  permission: displayname.change
# This Plugin was written by Wertzui123 and you're not allowed to modify or rewrite it!
# To adjust it, just use the config.yml in the plugin_data/ChangeDisplayName folder.
# © 2019 Wertzui123