name: ChangeDisplayName
main: Wertzui123\ChangeDisplayName\Main
version: 3.0
api: 3.0
load: POSTWORLD
author: Wertzui123
description: A plugin to change your displayname in-game!
website: https://github.com/Wertzui123/ChangeDisplayName
permissions:
 cnd:
  description: Let you use all features of ChangeDisplayName
  default: op
  children:
   cdn.commands:
    description: Let you use all commands of ChangeDisplayName
    default: op
    children:
     cdn.cmd.cdn:
      description: Let you use /changedisplayname
      default: op
     cdn.cmd.realname:
      description: Let you use /realname
      default: op
     cdn.cmd.unnick:
      description: Let you use /unnick
      default: op
    cdn.unnick.others:
     description: Let you use /unnick on other players
     default: op
