---
# DON'T EDIT
config_version: 3.0

# COMMANDS
changedisplayname_command: "changedisplayname"
realname_command: "realname"
unnick_command: "unnick"

# DESCRIPTIONS
changedisplayname_description: "Change your displayname"
realname_description: "See a nicked players real name"
unnick_description: "Reset your displayname"

# USAGES
changedisplayname_usage: "§cUsage: /changedisplayname <nickname>"
realname_usage: "§cUsage: /realname <displayname>"

# ALIASES
changedisplayname_aliases: ["cdn", "nick"]
realname_aliases: []
unnick_aliases: ["removenick"]

# CDN
nickname_format: "{nickname}"
...
