---
# ChangeDisplayName - Copyright 2019 - 2021 Wertzui123
# Don't edit this if you don't know what you're doing
config-version: 4.0
# Banned nicknames
banned_nicknames:
  - Hacker
  - Owner
  - Admin
  - Support Team
  - Supporter
  - Nazi
  - Team
  - Staff
  - Server
  - Player
# How the nicknames should be shown
# {group} represents the PurePerms group
nickname_format: "{displayname}"
# Commands
command:
  nick:
    command: nick
    description: Nick yourself
    usage: "/nick <nickname: string>"
    aliases: ['nickname', 'changedisplayname', 'cdn']
  realname:
    command: realname
    description: Find out the actual name of a nicked player
    usage: "/realname <player: string>"
    aliases: []
  unnick:
    command: unnick
    description: Reset your or someone elses displayname
    usage: "/unnick [player: target]"
    aliases: []
...